name: tag release

on:
  release:
    types: [created]

jobs:
  deploy_to_test:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Yarn
        run: npm install -g yarn

      - run: yarn

      - name: publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}


